module "wrapper" {
  source = "../."

  for_each = var.items

  app_path                             = try(each.value.app_path, var.defaults.app_path)
  argocd_applicationset_cpu_request    = try(each.value.argocd_applicationset_cpu_request, var.defaults.argocd_applicationset_cpu_request, "50m")
  argocd_applicationset_memory_limit   = try(each.value.argocd_applicationset_memory_limit, var.defaults.argocd_applicationset_memory_limit, "128Mi")
  argocd_chart_version                 = try(each.value.argocd_chart_version, var.defaults.argocd_chart_version, "8.1.2")
  argocd_controller_cpu_request        = try(each.value.argocd_controller_cpu_request, var.defaults.argocd_controller_cpu_request, "250m")
  argocd_controller_memory_limit       = try(each.value.argocd_controller_memory_limit, var.defaults.argocd_controller_memory_limit, "1536Mi")
  argocd_dex_cpu_request               = try(each.value.argocd_dex_cpu_request, var.defaults.argocd_dex_cpu_request, "50m")
  argocd_dex_memory_limit              = try(each.value.argocd_dex_memory_limit, var.defaults.argocd_dex_memory_limit, "128Mi")
  argocd_notification_url_for_github   = try(each.value.argocd_notification_url_for_github, var.defaults.argocd_notification_url_for_github)
  argocd_notifications_cpu_request     = try(each.value.argocd_notifications_cpu_request, var.defaults.argocd_notifications_cpu_request, "50m")
  argocd_notifications_memory_limit    = try(each.value.argocd_notifications_memory_limit, var.defaults.argocd_notifications_memory_limit, "256Mi")
  argocd_redis_cpu_request             = try(each.value.argocd_redis_cpu_request, var.defaults.argocd_redis_cpu_request, "50m")
  argocd_redis_memory_limit            = try(each.value.argocd_redis_memory_limit, var.defaults.argocd_redis_memory_limit, "128Mi")
  argocd_reposerver_cpu_request        = try(each.value.argocd_reposerver_cpu_request, var.defaults.argocd_reposerver_cpu_request, "50m")
  argocd_reposerver_memory_limit       = try(each.value.argocd_reposerver_memory_limit, var.defaults.argocd_reposerver_memory_limit, "256Mi")
  argocd_server_cpu_request            = try(each.value.argocd_server_cpu_request, var.defaults.argocd_server_cpu_request, "100m")
  argocd_server_memory_limit           = try(each.value.argocd_server_memory_limit, var.defaults.argocd_server_memory_limit, "256Mi")
  default_role                         = try(each.value.default_role, var.defaults.default_role, "readonly")
  gateway_listener_name                = try(each.value.gateway_listener_name, var.defaults.gateway_listener_name, "websecure-argocd")
  gateway_name                         = try(each.value.gateway_name, var.defaults.gateway_name, "traefik-gateway")
  gateway_namespace                    = try(each.value.gateway_namespace, var.defaults.gateway_namespace, "traefik-system")
  github_access                        = try(each.value.github_access, var.defaults.github_access, {})
  github_pr_comment_on_failure_enabled = try(each.value.github_pr_comment_on_failure_enabled, var.defaults.github_pr_comment_on_failure_enabled, true)
  github_pr_comment_on_success_enabled = try(each.value.github_pr_comment_on_success_enabled, var.defaults.github_pr_comment_on_success_enabled, false)
  helm_release_max_history             = try(each.value.helm_release_max_history, var.defaults.helm_release_max_history, 3)
  idp_argocd_allowed_oauth_scopes      = try(each.value.idp_argocd_allowed_oauth_scopes, var.defaults.idp_argocd_allowed_oauth_scopes, ["email", "openid", "profile"])
  idp_argocd_name                      = try(each.value.idp_argocd_name, var.defaults.idp_argocd_name, "Azure")
  idp_endpoint                         = try(each.value.idp_endpoint, var.defaults.idp_endpoint)
  log_level                            = try(each.value.log_level, var.defaults.log_level, "info")
  metrics_enabled                      = try(each.value.metrics_enabled, var.defaults.metrics_enabled, false)
  p_role                               = try(each.value.p_role, var.defaults.p_role, "no-access")
  rbac4groups                          = try(each.value.rbac4groups, var.defaults.rbac4groups, [])
  repo_revision                        = try(each.value.repo_revision, var.defaults.repo_revision, "main")
  repo_url                             = try(each.value.repo_url, var.defaults.repo_url)
  service_monitor_enabled              = try(each.value.service_monitor_enabled, var.defaults.service_monitor_enabled, false)
  sp_client_id                         = try(each.value.sp_client_id, var.defaults.sp_client_id)
  sp_client_secret                     = try(each.value.sp_client_secret, var.defaults.sp_client_secret)
  url                                  = try(each.value.url, var.defaults.url)
}
